-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 19:57:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospedagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospedagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospedagem` DEFAULT CHARACTER SET utf8 ;
USE `hospedagem` ;

-- -----------------------------------------------------
-- Table `hospedagem`.`id_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospedagem`.`id_cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `email_cliente` VARCHAR(100) NULL,
  `cpf_cliente` CHAR(11) NULL,
  `telefone_cliente` CHAR(11) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospedagem`.`hospedagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospedagem`.`hospedagem` (
  `id_hospedagem` INT NOT NULL AUTO_INCREMENT,
  `tipo_hospedagem` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade_hospedagem` VARCHAR(45) NOT NULL,
  `bairro_hospedagem` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_hospedagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospedagem`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospedagem`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `quarto_reserva` CHAR(11) NOT NULL,
  `tamanho_reserva` VARCHAR(45) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `nivel_reserva` VARCHAR(45) NOT NULL,
  `valor_reserva` DECIMAL(10) NOT NULL,
  `id_cliente_id_cliente` INT NOT NULL,
  `hospedagem_id_hospedagem` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_id_cliente_idx` (`id_cliente_id_cliente` ASC) ,
  INDEX `fk_reserva_hospedagem1_idx` (`hospedagem_id_hospedagem` ASC) ,
  CONSTRAINT `fk_reserva_id_cliente`
    FOREIGN KEY (`id_cliente_id_cliente`)
    REFERENCES `hospedagem`.`id_cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_hospedagem1`
    FOREIGN KEY (`hospedagem_id_hospedagem`)
    REFERENCES `hospedagem`.`hospedagem` (`id_hospedagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
